expression = assigment | unary | binary | declaration | if | lambda ;
assignment = IDENTIFIER { pattern } "=" expression ;
declaration = IDENTIFIER ":" type { type } ;
if = "if" expression expression { "else if" expression expression } "else" expression ;
lambda = { IDENTIFIER } "$" expression ;
binary = primary { IDENTIFIER primary } ;
unary = "!" | "-" | IDENTIFIER expression ;
type = "_" | IDENTIFIER ;

pattern = "_"
       | "true" | "false"
       | NUMBER
       | STRING
       | IDENTIFIER ;

primary = "true" | "false" | "null"
       | "(" expression ")"
       | NUMBER | STRING
       | IDENTIFIER ;
